### ISSUE TITLE
Not working in S4

### ISSUE THREAD

**Issue by ViswanathL** [pwittchen/NetworkEvents#1] opened 2015-01-24 08:32 UTC
Not working in Galaxy S4 i9500. Android Kitkat 4.4.2. Nothing happens on connectivity change. Please check and update.

**Comment by pwittchen** [comment] 2015-01-24 11:31
Thanks for reporting an issue. Unfortunately, I don't have access to this device right now and I am able to test it only on Nexus 5. When I will have an access to the phone mentioned by you, I will check that issue.

**Comment by pwittchen** [comment] 2015-01-27 18:49
@ViswanathL In addition, please make sure that you are actually **connected** to the Wifi or mobile network. When you turn on Wifi in your phone, but you are not connected to the Wifi access point, nothing will happen and library does not handle such situation.

**Comment by ViswanathL** [comment] 2015-01-27 19:27
@pwittchen Yeah I'm sure about that, Because I was getting webservice response. Still I was not getting the event.

**Comment by pwittchen** [comment] 2015-01-27 19:38
I've noticed this issue is not connected with the NetworkEvents library, but with source code of the Android 4.4.2 and implementation of BroadcastReceivers. It was reported to Android team at Google and you can see an issue here: https://code.google.com/p/android/issues/detail?id=57014
As far as I know, this problem is fixed in Android 4.3. 
To sum up, no matter if you are using this library or native implementation of BroadcastReceivers, this bug will occur until you will upgrade Android OS to the greater version on your phone.

**Comment by pwittchen** [comment] 2015-10-10 15:18
Can anyone else reproduce that?

**Comment by pwittchen** [comment] 2016-07-16 20:23
I couldn't reproduce that problem. We can re-open this in future if more people will struggle with that issue.

**Closed by pwittchen** 2016-07-16 20:23 UTC
Labels: bug, help wanted, invalid, wontfix
